%YAML:1.0
---
dataset_dir: "F:/MyGitHub/SLAM/Source/myslam/data/rgbd_dataset_freiburg1_desk"
number_of_features: 500
scale_factor: 1.2000000000000000e+00
level_pyramid: 8
match_ratio: 2.
max_num_lost: 10.
min_inliers: 10
keyframe_rotation: 1.0000000000000001e-01
keyframe_translation: 1.0000000000000001e-01
map_point_erase_ratio: 0.1
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7
camera.depth_scale: 5000.0
